#!/bin/sh

bspc config border_width         1
bspc config normal_border_color  \#0F1819
bspc config active_border_color  \#0F1819
bspc config focused_border_color \#BA77A9
bspc config window_gap           12
