#!/bin/sh

bspc config border_width         1
bspc config normal_border_color  \#3B4252
bspc config active_border_color  \#3B4252
bspc config focused_border_color \#A3BE8C
bspc config window_gap           15
