#!/bin/sh

bspc config border_width        2
bspc config normal_border_color \#23323e
bspc config active_border_color \#23323e
bspc config focused_border_color \#446980
bspc config window_gap          10
