#!/bin/sh

bspc config border_width         1
bspc config normal_border_color  \#27282c
bspc config active_border_color  \#27282c
bspc config focused_border_color \#636363
bspc config window_gap           10
