#!/bin/sh

bspc config border_width         1
bspc config normal_border_color  \#002b36
bspc config active_border_color  \#073642
bspc config focused_border_color \#586E75
bspc config window_gap           15
