#!/bin/sh

bspc config border_width         2
bspc config normal_border_color  \#0f1317
bspc config active_border_color  \#0f1317
bspc config focused_border_color \#3b536a
bspc config window_gap           15
